### ISSUE TITLE
Week 06 Day 2 - A Sound Board with Sass

### ISSUE THREAD

**Issue by ambethia** [gabeo14/assignments#21]
In this assignment, you'll start with a partially complete Sound Board application and make it your own.

## Objectives

- Use features of Sass to style an application
- Practice React

## Requirements

Starting from the [implementation we created in class](https://github.com/suncoast-devs/cohort-xi/tree/master/week-06/day-2/sound-board), create your own Sound Board application.

Note the addition of `node-sass` to the project's dependencies.

### Explorer Mode

- [ ] Have at least 3 sound boards defined in `library.js`, with at least 4 sounds each.
- [ ] Use Sass for your CSS, explore and use the following features:
  - [ ] Variable
  - [ ] Nesting
  - [ ] [Functions](https://sass-lang.com/documentation/Sass/Script/Functions.html)

### Adventure Mode

- [ ] Use these Sass features
  - [ ] Mixins
  - [ ] Inheritance
  - [ ] Break your styles into multiple files using `@import`

### Epic Mode

- [ ] Create a "Video Clip" board, that plays different video clips when thumbnails are clicked.

## Additional Resources

- https://sass-lang.com/guide

**Comment by gabeo14** [comment]
caring-sand.surge.sh

https://github.com/gabeo14/soundboard

I'll get in and do a bit more styling when I get the chance

**Comment by gstark** [comment]
Yes, please refine the CSS some before you include this in a portfolio

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
