### ISSUE TITLE
Week 07 Day 2 - Intro to Phaser Games

### ISSUE THREAD

**Issue by gstark** [gabeo14/assignments#24]
## Using a Front End Gaming Library

In this assignment, you'll build a simple game

## Objectives

- Learn a new front end library
- Experiment with writing games

### Explorer Mode

- [ ] Get the demo we did in class working locally.
- [ ] Play with changing the physics settings in the game to adjust the game play.
- [ ] Update the images to your own style.
- [ ] Add a new feature to, or change an existing feature of, the game

### Adventure Mode

- [ ] Modify your game to a new game, or create your own!

**Comment by gabeo14** [comment]
first-phaser-app-goleink.surge.sh

https://github.com/gabeo14/unit-2/tree/master/first-phaser-game

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74dc376b990fefa4b57db26c0337e9d122b96fd7/giphy-16.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/81)**__
