### ISSUE TITLE
Week 07 Day 4 - Wireframes

### ISSUE THREAD

**Issue by gstark** [gabeo14/assignments#26]
## Build wireframes of your Capstone Project

# Be prepared to show these to your instructor early next week.

**Comment by gabeo14** [comment]
Mark liked them so I guess I can close this? I'm gonna close this.

ISSUE CLOSED

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
