### ISSUE TITLE
Week 08 Day 1 - Welcome to a New World

### ISSUE THREAD

**Issue by mdewey** [gabeo14/assignments#27]
Today you learned a new language and will be starting to explore it more in depth in the coming weeks. Like any good craftsman, the first thing you need is to learn your tools. Tonight, you will be setting up your developer environment, creating a simple console application, and writing a short blog. 

## Objectives

* Set up your dev machines
* Create a simple console application to ensure your machine is set up correctly
* Write a blog article to practice talking about technology 

### .NET Students 

 - Install the .NET Core SDK here: [https://www.microsoft.com/net/download](https://www.microsoft.com/net/download)
- Install the `C#` plugin in VS Code. 

- To verify everything was installed correctly, run `dotnet -v` in your terminal.

### Ruby

You should already have Ruby installed. 

#### Simple Console Application 
* [x] Create a console application that guesses a number that a user has thought of ,between 1 and 100. This will use a [`binary search`](https://www.programmerinterview.com/index.php/puzzles/minimum-guesses-1-100/) to guess the correct number 

* [x] Here is the JavaScript, in browser, algorithm to follow. Make sure to understand this first before writing new code: [`https://codepen.io/ambethia/pen/KNewBb`](https://codepen.io/ambethia/pen/KNewBb). 
**NOTE** You will be translating this from the event driven paradigm of HTML to the more procedural paradigm of a console application. 
* [x] For Explorer Mode, you do not have to put in menu or other user experience "nice to haves", focus on the just the core algorithm.

#### Wireframes
* [ ] Finish working on your wireframes and ironing out your idea. Work with your instructors and peers to work out the kinks. 

### Adventure Mode

* [ ] Create a nice user experience for the number guesser. Include features such as 
`Try again` and `Welcome, press enter to start`

### Epic Mode

* [ ] Eventually we will be using a MVC application structure. To prepare for this, refactor your code to have all your business logic in separate class and all your console interaction in the main class. 

## Additional Resources

* Ruby Resouces: 
    - [https://learnrubythehardway.org/book/ex33.html](https://learnrubythehardway.org/book/ex33.html)

* .NET
    - [https://docs.microsoft.com/en-us/dotnet/](https://docs.microsoft.com/en-us/dotnet/)

**Comment by gabeo14** [comment]
https://github.com/gabeo14/BinarySearch

Got it!  Had a lot of fun with this one!  I surprised myself with my ability to debug.  Liking c# so far!

Thanks Mark!

**Comment by mdewey** [comment]
Love the snarky, but don't forget to add a gitignore to your project

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
