### ISSUE TITLE
Week 10  Day 1 - Blog, The Series Finally

### ISSUE THREAD

**Issue by mdewey** [gabeo14/assignments#33]
We are approaching the final stretch of topics and tonight we will be preparing for the final stretch.

For today, we are going to blogging and practicing everything we have talk about. 

## Objectives
- Practice talking like a developer
- Work on your capstone

## Explorer
- [x] Blog time. Choose a prompt from the following list
    - Pick 1 topic that we have learned and create a blog post explaining it to a new or non-developer
    - Blog about a struggle that you have encountered and overcame during your tenure here so far. 
    - Pick a new technology that we haven't hit yet (or won't) and create a intro blog for that. 

- [ ] Algorithm Practice -- submit a `gist` of your solution for https://www.codewars.com/kata/form-the-minimum in C#, Ruby, and/or  JavaScript

## Adventure
- [ ] Start Suncoast Overflow
- [ ] Work on your capstone project

**Comment by gabeo14** [comment]
https://medium.com/@gomusic14/the-duality-of-work-and-life-at-sdg-caece6b00cd3

**Comment by gabeo14** [comment]
https://gist.github.com/gabeo14/bd5ad91879e0bff439bb21a1495ed693

Got this to work with some research but I don't get it.  I can't find documentation about the "..." that is apparently necessary. My google fu has failed me.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/24)**__
