### ISSUE TITLE
Final Project - #Ship it - 

### ISSUE THREAD

**Issue by mdewey** [gabeo14/assignments#37]
With all the work you have been putting into the last 13 weeks, it has all come down to this. Complete your capstone and show it to the world

## Explorer Mode

- [ ] Submit your repository for the capstone project
- [ ] Submit your Url(s) for your capstone project.

**Comment by gabeo14** [comment]
https://www.gpcal.pro/

https://gp-cal.herokuapp.com/api/series

https://github.com/gabeo14/GPCalAPI

https://github.com/gabeo14/gpcal_front
