### ISSUE TITLE
Week 02 Day 3 - Roshambo!

### ISSUE THREAD

**Issue by gstark** [gabeo14/assignments#6]
Create a simple Rock-Paper-Scissors game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

## Requirements

Do not worry about CSS for explorer mode, only do as HTML to show the functionality.

### Explorer Mode

- [ ] As a user I should be able to see three buttons for each player.
- [ ] As a user, I should be able to pick an option for each player.
- [ ] As a user, after each player makes their selection, I should be told who won and the game should be over.

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection.
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice)
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by gabeo14** [comment]
roshambo-theun.surge.sh

https://github.com/gabeo14/roshambo

Here's this one finally!  Thanks Gavin!

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
